@startuml
title
 <font color=BlueViolet>Change Cashier - <i>Sequence Diagram</i></font>
end title
actor Customer as USER
actor Cashier as CASHIER
participant UI as UI
participant GENESIS as GENESIS
participant TACHYON as TACHYON


alt enableChangeCashier feature is off
UI->UI: disable Cashier Tools
end
alt enableChangeCashier feature is ON
   USER->UI: Login with user credentials
   UI->TACHYON: Websocket connection
   note right: Established websocket connection on lane open
   UI -> GENESIS: bff-login api call to get the user details
   TACHYON -> UI: return the user authenticated
   UI -> GENESIS: bff-login api call to get the user details with store mode on
   note right: Payload passed as Store mode is on, inorder to get the user details
   TACHYON -> UI: return the user details
   USER->UI: Click Store Mode
   ASSOCIATE -> UI: Click on Store Sign In or Scan QR code
   UI -> GENESIS: bff-login api call to get the user details
   TACHYON -> UI: return the user details
   USER -> UI: Click Cashier Tools Menu
   note right: Verify the Current Cashier Name must be User who have looged In
   CASHIER -> UI: Click the Change Cashier Menu
   CASHIER -> UI: Scan the QR code to change the cashier name
   UI->TACHYON: Websocket connection
   note right: Established websocket connection
   UI -> GENESIS: bff-login api call to get the cashier login details
   TACHYON -> UI: return the cashier login details
   UI -> UI: Cashier Updated
   UI -> GENESIS: addAssociateIdToWorkfile api call
   GENESIS -> UI: return message as <font color=blue>"workfile updated with Associate ID"
   else Invalid Cashier Name
   TACHYON -[#red]> UI: <font color=red>Return as invalid cashier details
   UI -[#red]> UI: <font color=red>Scan a Valid QR Code
end