@startuml
actor Customer as customer
participant Associate as associate
participant UI as ui
participant Genesis as genesis
participant Tachyon as tachyon
participant PED as ped

== Pre Tender Interventions ==
customer -> ui: click on Item entry
customer -> ui: Enters the item number
customer -> ui: clicks on Enter
ui -> genesis: action: new
genesis --> ui: message: "workfile created." 
ui -> genesis: next action : addItem
note right: create work file

group Invalid item entry intervention
genesis --> ui: returns validationStatus as "HARD_STOP"
ui -> ui: associate intervention
ui -> tachyon: /signal call - payload "signalType" as "ERROR" , level : "2"
ui -> tachyon: /notify/intervention/start - reason ["ITEM_CANT_BE_SOLD"]
associate -> ui: clicks on Store Sign In or Scan QR code
ui --> ui: Item cannot be sold at Self Checkout
associate -> ui: clicks on "Return to Cart"
ui -> ui: Return to Cart Page
ui -> tachyon: /signal call - payload "signalType" as "SUCCESS" , level : "1"
ui -> tachyon: /end call with intervention time duration
end

group High dollar items intervention
genesis --> ui: returns validationStatus as "VRF_REQ"
ui -> ui: associate intervention
ui -> tachyon: /signal call - payload "signalType" as "ERROR" , level : "2"
ui -> tachyon: /notify/intervention/start - reason ["HIGH_DOLLAR_ITEM"]
associate -> ui: clicks on Store Sign In or Scan QR code
ui --> ui: High Value item - approve | Remove from cart
alt if associate approves the item
associate -> ui: Approve
ui -> tachyon: /signal call - payload "signalType" as "NORMAL" , level : "1"
ui -> genesis: action : addItem
ui -> tachyon: /notify/intervention/end
ui -> tachyon: /notify/transaction/start
ui -> tachyon: /signal call - payload "signalType" as "NORMAL" , level : "1" 
end
alt if associate selects Remove from Cart
associate -> ui: Remove from cart
ui -> tachyon: /signal call - payload "signalType" as "NORMAL" , level : "1"
ui -> tachyon: /notify/intervention/error - reasons ["HIGH_DOLLAR_ITEM"]
end
ui -> ui: Return to Cart Page
end

group Zero Dollar Item intervention
genesis --> ui: returns validationStatus as "ZERO_DOLLAR_ITEM"
ui -> ui: associate intervention
ui -> tachyon: /signal call - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: /notify/intervention/start - reason ["ZERO_DOLLAR_ITEM"]
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> ui: Price-required item - Enter price | Cancel
alt if associate enters price
associate -> ui: Enter price
ui -> ui: Return to Cart Page
ui -> customer: Enter selling price
ui -> tachyon: /signal call - payload - "signalType" as "NORMAL" , level : "1"
ui -> tachyon: /notify/intervention/end
end
alt if associate tap Cancel
associate -> ui: Cancel
ui -> tachyon: /register/signal - payload - signalType: "NORMAL", level: "1"
ui -> tachyon: /notify/intervention/error - reason:["ZERO_DOLLAR_ITEM"]
ui -> genesis: action: editItem
ui -> tachyon: /register/signal - payload - "signalType" as "SUCCESS" , level : "1"
ui -> ui: Returns to Start Scanning Page
end
end

group Age restricted Item intervention
genesis --> ui: returns validationStatus as "VRF_REQ"
ui -> tachyon: /signal call - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: /notify/intervention/start - reason ["AGE_RESTRICTED_ITEM"]
ui -> customer: Associate approval is needed for an age-restricted item.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> ui: Age restrcited item - Approve | Remove from cart
alt if associate Approves the item
associate -> ui: Approve the item
ui -> tachyon: /signal call - payload - "signalType" as "NORMAL" , level : "1"
ui -> genesis: action: addItem
genesis --> ui: validationStatus: "VALID"
ui -> tachyon: /notify/intervention/end
ui -> tachyon: /notify/transaction/start
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
end
alt if associate removes the item from cart
associate -> ui: Remove Item from Cart
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> tachyon: /notify/intervention/error - reasons: ["AGE_RESTRICTED_ITEM"]
end
ui -> ui: Returns to Cart Page
end

group Recalled Item intervention
genesis --> ui: validationCode: "RECALLED" validationStatus: "HARD_STOP"
ui -> tachyon: /signal call - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: /notify/intervention/start - reasons: ["RECALLED_ITEM"]
ui -> customer: This item cannot be sold due to recall.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> ui: Recalled Item , This item cannot be sold, Return to Cart
ui -> tachyon: /register/signal - payload - "signalType" as "SUCCESS" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: Returns to Cart Page
end

group Remove quantity Intervention
genesis --> ui: validationStatus: "VALID"
ui -> customer: How many do you have?
customer -> ui: verifies the quantity and taps Enter
ui -> genesis: action: editItem - payload - item quantity, workfile
genesis --> ui: message: "Line updated as requested."
ui -> tachyon: /notify/transaction/start
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
customer -> ui: taps on the item on left panel on cart page
customer -> ui: taps Remove on right panel , top right corner
ui -> tachyon: /notify/intervention/start - reasons: ["REMOVE_ITEM_FROM_SALE"]
ui -> tachyon: /register/signal - payload - "signalType" as "ERROR" , level : "2"
ui -> ui: Associate assistance is needed for a removed item.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> ui: Take the item from the customer and remove from sale. 
ui -> associate: Remove from Sale || Keep Item
alt if customer choose to keep the item
associate -> ui: keep the item
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: Returns to Cart Page
end
alt if associate removes item from sale
associate -> ui: Remove Item from Sale
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> genesis: action: editItem
genesis -> ui: message: "Line updated as requested."
ui -> tachyon: /notify/transaction/abort - reasons: ["CLEAR_CART"]
ui -> genesis: action: cancel
genesis -> ui: msg: "Sale has been canceled"
ui -> genesis: action: reset
ui -> customer: Processing
ui -> tachyon: /register
tachyon --> ui: operationalStatus: "OPERATIONAL"
ui -> tachyon: /register/signal - payload - "signalType" as "SUCCESS" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: Returns to Start Scanning Page
end
end

group Item Quantity Reduced intervention
genesis --> ui: validationStatus: "VALID"
ui -> customer: How many do you have?
customer -> ui: edits the quantity and taps Enter
ui -> genesis: action: editItem - payload - item quantity, workfile
genesis --> ui: message: "Line updated as requested."
ui -> tachyon: /notify/transaction/start
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
customer -> ui: taps on the item on left panel on cart page
customer -> ui: reduces the item quantity and taps Enter
ui -> tachyon: /notify/intervention/start - reasons: ["REDUCE_ITEM_FROM_SALE"]
ui -> tachyon: /register/signal - payload - "signalType" as "ERROR" , level : "2"
ui --> ui: Associate assistance is needed for a reduced item quantity.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> ui: Approve New Quantity || Keep Current Item Quantity
alt if new quantity is approved
associate -> ui: Approve New Quantity
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> genesis: action: editItem - payload - newQuantity
genesis --> ui: message: "Line updated as requested."
ui -> tachyon: /notify/intervention/end - payload - intervention duration
end
alt if current quantity is kept
associate -> ui: Keep Current Item Quantity
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
end
ui -> ui: Returns to Cart Page
end

group SOS Item intervention
genesis -> ui: validationCode: "SOS" validationStatus: "HARD_STOP"
ui -> tachyon: /register/signal - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: notify/intervention/start - reasons: ["ITEM_CANT_BE_SOLD"]
ui --> ui: An associate will help you with your purchase.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui --> ui: This item can't be sold at self-checkout. Return to Cart
associate -> ui: Return to Cart
ui -> tachyon: /register/signal - payload - "signalType" as "SUCCESS" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: Returns to Cart Page
end

group MISC Item intervention
genesis -> ui: validationCode: "MISC_ITEM" validationStatus: "HARD_STOP"
ui -> tachyon: /register/signal - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: notify/intervention/start - reasons: ["ITEM_CANT_BE_SOLD"]
ui --> ui: An associate will help you with your purchase.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui --> ui: This item can't be sold at self-checkout. Return to Cart
associate -> ui: Return to Cart
ui -> tachyon: /register/signal - payload - "signalType" as "SUCCESS" , level : "1"
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: Returns to Cart Page
end

group Item sold by foot intervention
genesis -> ui: validationCode: "ONE_FOOT" validationStatus: "VRF_WARN"
ui -> tachyon: /register/signal - payload - "signalType" as "ERROR" , level : "2"
ui -> tachyon: notify/intervention/start - reasons: ["SOLD_BY_FOOT_ENT_LEN"]
ui -> ui: An associate will need to enter the quantity.
ui -> ui: associate intervention
associate -> ui: clicks on Store Sign In or Scan QR code
ui -> tachyon: /notify/intervention/end - payload - intervention duration
ui -> ui: This item is sold by the foot. Enter the # of feet.
associate -> ui: Enters the feet, taps "Enter"
ui -> genesis: action: editItem
genesis -> ui: message: "Line updated as requested."
ui -> tachyon: /notify/transaction/start
ui -> tachyon: /register/signal - payload - "signalType" as "NORMAL" , level : "1"
ui -> ui: Returns on Cart Page
end




