@startuml
!pragma teoz true

title <font color="#52595D">Soft interventions add item(s)</font>

actor customer as user
actor associate as asc
box "UI layer interactions" #LightSalmon
    participant UI as ui
    collections Redux as redux
end box
participant BFF as bff
participant Genesis as genesis

==Hybrid/Legacy cart flow==
    group #LightGray Add item flow
        user->ui: scanned item or manual entry(non restricted)
        ui->genesis: add item call
        genesis-->ui: response with sucess
        ui-[#008000]>redux: add item to state
       
        user-[#C04000]>ui: scanned item or manual entry(age restricted)
        ui-[#C04000]>genesis: add item call
        genesis-[#C04000]->ui: response with approval needed
        ui-[#008000]>redux: add item to state 
        note right: update item in redux with \napproval needed identifier
       
        user-[#C04000]>ui: scanned item or manual entry(measurement item)
        ui-[#C04000]>genesis: add item call
        genesis-[#C04000]->ui: response with approval needed
        ui-[#008000]>redux: add item to state 
        note right: update item in redux with \napproval needed identifier
    end

    group #LightYellow Cart page
        ui-[#008000]>redux: fetch cart list along with restricted items
        user->ui: delete item restrcited/normal
        ui-[#008000]>redux: update line item
        note right: update state with \napproval needed identifier
    end

    group #LightSteelBlue Payment flow
        user->ui: clicks paynow button
        ui-[#008000]>redux: fetch list of approval needed items
        ui->ui: intervention for restricted items
        note right: Help is on the way, approval needed
        asc->ui: associate logs in
        ui->genesis: associate's credentials
        genesis-->ui: login sucess 
        ui->ui: show list of items needs approval
        note right: After aossicate logs in
        
        alt #LightSlateGray step1 - age restricted approval
            asc->ui: click accept
            ui->genesis: add item confirmation
            genesis-->ui: add item success
            ui-[#008000]>redux: update state
            note right: update line item and \nremove approval needed identifier
        else step1 - decline request
             asc->ui: click decline
             ui-[#008000]>redux: update state
             note right: remove item from the state
        end

        alt #LightSlateGray step2 - measurement item approval
            asc->ui: fills the required inputs
            note right: Enter # of feet
            ui->genesis: add item with details
            genesis-->ui: add item success
            ui-[#008000]>redux: update state
            note right: update line item and \nremove approval needed identifier
        end

        alt #LightSlateGray step2 - deleted item approval
            asc->ui: click delete
            alt if restrcited item 
              ui-[#008000]>redux: update cart state and remove line item
              note right: remove line item from state
              else if non restrcited item
                 ui->genesis: delete item request
                 genesis->ui: delete item success
                 ui-[#008000]>redux: update cart state
                note right: remove line item from state
            end
        else step2 - add back to cart
             asc->ui: add item back
             ui-[#008000]>redux: update cart state
             note right: remove approval needed identifier
        end

        ui->ui: Payment screen
    end

==Bff cart flip with restricted item==
    ui->bff: clear cart
    bff-->ui: clear cart success
    ui-[#008000]>redux: clear redux state
    {start} ui->genesis: add all items back again
    genesis-->ui: add item(s) sucess
    {end} ui-[#008000]>redux: update redux state
    {start} <-> {end}: add item in loop
    note right: already approved(restricted) items \ndoes not need approval
== Repetition ==
    ui->genesis: add new item(restricted)
    genesis-->ui: response with approval needed
    note over ui, redux: Repeat the above sequence for restrcited items 
@enduml