@startuml
actor Customer as USER
participant UI as UI
participant GENESIS as GENESIS
participant TACHYON_DM as TACHYON_DM

alt enableMilitaryDLScan feature is off
UI->UI: No ID scan needed, Proceed as Normal
end
alt enableMilitaryDLScan feature is ON
USER -> UI: click on Military Discount Menu
UI -> UI: prompted to scan ID or DL
USER -> TACHYON_DM: Scan the ID
alt if Scan ID Matches
TACHYON_DM -> UI: returns success
end
UI -> UI: Click on Help
UI -> UI: show the customer intervention
UI -> UI: click the Store Sign In
UI -> GENESIS: bff-login api call to get the user details
TACHYON_DM -> UI: return the user authenticated
UI -> UI: Associate Intervention
USER -> UI: Verify the displayed customer info with yes or no button option
alt if associate selects no
USER -> UI: selects no option 
UI -> UI: goes back to cart
UI -> TACHYON_DM: Signal api call(normal)
UI -> TACHYON_DM: notify intervention error api call
end
alt if associate selects yes
USER -> UI: selects yes option
UI -> GENESIS: addCustomerToCart api call
GENESIS --> UI: customer added to cart response
UI -> TACHYON_DM: Signal api call(normal)
UI -> TACHYON_DM: notify intervention end api call
UI -> UI: shows toast notification
end
alt if Scan ID doesnot Match
TACHYON_DM -> UI: Invalid Scan. Try again or tap Help
USER -> UI: Scan the ID again
TACHYON_DM -> UI: ID doesnot match try another form or tap Help
end
end