@startuml
actor Bob as user
participant UI as ui
participant DevicePlatform as tachyon
participant PED as ped
participant Genesis as genesis
actor Bob as user1

ui->tachyon: Websocket connection
note right: Establised websocket connection on lane open

user->ui: Select payment

ui->tachyon: activate/payment
note right: activate all paymenet modes
tachyon --> ui: payment activation
note right: response with available payment modes

user1->ped: swipe/insert card
ped-->tachyon: card details
tachyon-->ui: tender events/details
note right: sends tender_capture/modes, card details/error
ui->tachyon: suspend(payment modes)
tachyon-->ui: payment mode suspended(true/false)

ui->genesis: polling starts(send card details)
genesis-->ui: payment info with next action
note right: invoice, next action and continue
ui->genesis: continue pooling
genesis-->ui: authrized details(next action/data needed)

ui->tachyon: payment approval
user1->ped: signature
ped-->tachyon: signature details
tachyon-->ui: event(tender_paid) other info
note right: authorization details, signature, etc

ui->genesis: continue pooling(send authorization details)
genesis-->ui: sale complete
ui->genesis: stop polling and send signature data

ui->tachyon: deactivate all payment modes
tachyon-->ui: payment deactivation confirmation
ui->genesis: receipt selection and print