@startuml
actor Customer as USER
actor Associate as ASSOCIATE
participant UI as UI
participant BFF as BFF
participant TACHYON_DM as TACHYON_DM
participant PED as PED
participant CR as CR

group with no partial tender

== [CASH, CARD] - activation CASH/CARD activation is false ==
USER -> UI: click on paynow
UI -> TACHYON_DM: /payment/start
UI -> TACHYON_DM: /activateπ
note right: paymentModes: ['CASH','CARD']
TACHYON_DM --> UI: /activate response card:true, cash:false
UI -> USER: Choose tender CARD ONLY YES | NO
group CUSTOMER selected YES to continue tender with gift card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{}}}
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI->UI: Show pin entry page on the basis of card type
    USER->UI: Enter pin number
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment
    UI->BFF: /review to review the cart for balance
    BFF --> UI: remaining amount due/totals
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI-> TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI -> USER: PROMPT for PRINT/ EMAIL - PRINT
    USER -> UI: Select PRINT
    UI-> TACHYON_DM: Print API
    UI -> TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI -> TACHYON_DM: /transaction/end 
    UI -> TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI-> UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected YES to continue tender with LBA card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{lbaLamexPoRequired:true}}} 
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI->UI: Show last four digit page on the basis of card type
    USER->UI: Enter last four digit
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment with 5% discount
    UI->USER: Show prompt for PO box(optional) (lbaLamexPoRequired:true)
    UI->BFF: /review to review the cart 
    BFF --> UI: remaining amount due/totals
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI->TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI->USER: PROMPT for PRINT/ EMAIL - PRINT
    USER->UI: Select PRINT
    UI->TACHYON_DM: Print API
    UI->TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI->TACHYON_DM: /transaction/end 
    UI->TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI->UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected YES to continue tender with Merch gift card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{driverLicenseState:"NC", drivingLicenseNumber:"1306620"}}} 
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI->UI: Show pin entry page on the basis of card type
    USER->UI: Enter pin number
    UI->USER: Show Intervention for DL licencese
    ASSOCIATE->UI: Sign in
    UI->USER: Show DL validation prompt
    USER->UI: Enter DL details
    UI->UI: Match DL details with tender captured event given DL details
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment
    UI->BFF: /review to review the cart 
    BFF --> UI: remaining amount due/totals
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI-> TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI -> USER: PROMPT for PRINT/ EMAIL - PRINT
    USER -> UI: Select PRINT
    UI-> TACHYON_DM: Print API
    UI -> TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI -> TACHYON_DM: /transaction/end 
    UI -> TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI-> UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected YES to continue tender with debit card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: PIN_REQUESTED - event
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{}}}
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment
    UI->BFF: /review to review the cart 
    BFF --> UI: remaining amount due/totals
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI->TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI -> USER: PROMPT for PRINT/ EMAIL - PRINT
    USER -> UI: Select PRINT
    UI-> TACHYON_DM: Print API
    UI -> TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI -> TACHYON_DM: /transaction/end 
    UI -> TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI-> UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected YES to continue tender with LCC card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{}}}
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment
    BFF--> UI: lowesCardOption for promo
    UI->USER: show LCC financing options
    USER->UI: Select LCC Promotion
    UI->BFF: /cart/checkout/promo/reprice  -  attached selected lowes promo option
    UI->BFF: /review to review the cart 
    BFF --> UI: remaining amount due/totals
    TACHYON_DM-->UI: SIGNATURE_REQUESTED event
    USER->UI:  Signature on PED
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI->TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI -> USER: PROMPT for PRINT/ EMAIL - PRINT
    USER -> UI: Select PRINT
    UI-> TACHYON_DM: Print API
    UI -> TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI -> TACHYON_DM: /transaction/end 
    UI -> TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI-> UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected YES to continue tender with LAR card 
    UI -> UI: Insert Card
    TACHYON_DM --> UI: TENDER_CAPTURED - event {info:{cashback:0, cardDetails:{}}}
    UI -> TACHYON_DM: /suspend - paymentMode:['CARD']
    TACHYON_DM --> UI: response for suspend paymentModes:['CARD'] true
    UI -> BFF: /addPayment
    note right: cardDetails is attached to addPayment
    BFF-->UI: /addpayment response - LARauthBuyerdetails { poRequired, claimNbrRequired, taxExempt }
    UI->UI: Process add payment response and show prompt for PO, claim and taxExempt
    alt if taxExempt == 'Y'
    UI->USER: Show prompt for taxExempt choice YES and NO
    USER->UI: Confirm tax exempt
    alt if user select yes 
    UI-> USER: Show intervention for tax assistance
    end
    else if user selects no
    UI->UI: Cancel LAR tender
    end
    alt if poRequired and claimNbrRequired == 'Y'
    UI-> USER: Show PO and claim number prompt
    USER->UI: Enter PO and claim number
    end
    UI->BFF: /review to review the cart 
    BFF --> UI: remaining amount due/totals
    UI -> TACHYON_DM: /approve with total amount
    TACHYON_DM --> UI: TENDER_PAID - authorization details
    UI -> BFF: /authorization - authorization details as payload with poClaim
    UI->BFF: /rebates
    BFF-->UI: rebates {}
    UI->BFF: /review to get all the payment details.
    BFF--> UI: /complete
    UI->TACHYON_DM: /deactivate status true
    note right: /deactivate { card: 10 }
    TACHYON_DM --> UI: TENDER_REMOVED - event
    UI -> USER: PROMPT for PRINT/ EMAIL - PRINT
    USER -> UI: Select PRINT
    UI-> TACHYON_DM: Print API
    UI -> TACHYON_DM: /payment/end - {amount: 10, duration:123432345}
    UI -> TACHYON_DM: /transaction/end 
    UI -> TACHYON_DM: tachyon/v2/register - operationalStatus
    note right: operationalStatus - OPERATIONAL
    UI-> UI: Start Scanning/Tap to add items 
end
group CUSTOMER selected NO - View Cart
    UI -> USER: Intervention login
    ASSOCIATE -> UI: Login
    note right: UI will be shown with the payment mode failure info 
    UI -> USER: View Cart | Suspend Sale
    USER -> UI: customer selected View Cart
    UI -> BFF: /cart/view call
    UI -> UI: updated the new payment mode to CARD only
    USER -> UI: only click of paynow activate CARD 
    note right: activate response status: true
end
group CUSTOMER selected NO - Suspend Sale
    UI -> USER: Intervention login
    ASSOCIATE -> UI: Login
    note right: UI will be shown with the payment mode failure info 
    UI -> USER: View Cart | Suspend Sale
    USER -> UI: customer selected Suspend Sale
    UI -> BFF: /clearCart
    UI -> UI: cart switch to intermediate controller
== CART SWITCH ==
    UI -> GENESIS: ?action=saveInvoice
    UI --> GENESIS: pml <receipt template>
    UI -> TACHYON_DM: print receipt
    UI -> TACHYON_DM: tachyon/v2/register
    note right: operationalStatus - OPERATIONAL (paymentModes: ['CASH', 'CARD'])
    UI -> UI: update paymentModes
    UI -> UI: Start Scanning Screen
end
end