@startuml
actor Customer as USER
actor Associate as ASSOCIATE
participant UI as UI
participant BFF as BFF
participant GENESIS as GENESIS
participant TACHYON_DM as TACHYON_DM

== BFF Controller ==

group Military lookup
alt enableMilitaryDLScan feature is off
UI->UI: No ID scan needed, Proceed as Normal
end
alt enableMilitaryDLScan feature is ON
USER -> UI: click on military lookup
UI -> UI: prompted to scan ID or DL
USER -> TACHYON_DM: Scan the ID
alt if Scan ID Matches
TACHYON_DM -> UI: returns success
end
UI -> UI: Click on Help
UI -> UI: show the customer intervention
UI -> TACHYON_DM: notify intervention start api call
ASSOCIATE -> UI: clicks on Store Sign In or Scan QR code
UI -> UI: customer id verification with yes or no button option
alt if associate selects no
ASSOCIATE -> UI: selects no option 
UI -> UI: goes back to cart
UI -> TACHYON_DM: Signal api call(normal)
UI -> TACHYON_DM: notify intervention error api call
end
alt if associate selects yes
ASSOCIATE -> UI: selects yes option
UI -> BFF: addCustomerToCart api call
BFF --> UI: customer added to cart response
UI -> TACHYON_DM: Signal api call(normal)
UI -> TACHYON_DM: notify intervention end api call
UI -> UI: shows toast notification
end
end
end
@enduml
