@startuml
actor Customer as USER
actor Associate as ASSOCIATE
participant UI as UI
participant BFF as BFF
participant GENESIS as GENESIS
participant TACHYON as TACHYON

== BFF Controller ==
group Valid item scan 
USER -> UI: Scanned an item
UI -> GENESIS: Inventory lookup api call
GENESIS --> UI: Inventory lookup response
UI -> TACHYON: notify transaction start
UI -> TACHYON: Signal api call(normal)
UI -> BFF: add item api service call
BFF --> UI:  add item success response
note right: work file created with BFF
UI -> UI: Item added to cart
end

group Invalid item scan 
USER -> UI: Scanned an invalid item
UI -> GENESIS: Inventory lookup api call
GENESIS --> UI: Item not found result response for inventory lookup
UI -> BFF: add item call
BFF --> UI: Invalid barcode response for add item call
UI -> UI: Inalvide barcode info with continue button
USER -> UI: Scanned second invalid item
UI -> GENESIS: Inventory lookup api call
GENESIS --> UI: Item not found result response for inventory lookup
UI -> BFF: add item call with Invalid barcode response
BFF --> UI: Invalid barcode response for add item call
UI -> TACHYON: Signal api call(error)
UI -> TACHYON: notify intervention start api call
UI -> UI: Intervention
ASSOCIATE -> UI: clicks on Store Sign In or Scan QR code
UI -> UI: Invalid item info with button to go back to cart
UI -> TACHYON: Signal api call(normal)
UI -> TACHYON: notify intervention end api call
end

group Manual entry for valid add item
alt valid item entry
USER -> UI: clicks on item entry button
USER -> UI: enters item number and clicks on enter button
UI -> GENESIS: inventpory lookup call
GENESIS --> UI: Inventory lookup response
UI -> BFF: add item service call
BFF --> UI: add item call response
UI -> UI: quantity update screen
UI -> BFF: update item call
BFF --> UI: update item response
UI -> UI: Item added to cart
end
alt invalid item entry
USER -> UI: clicks on item entry button
USER -> UI: enters item number and clicks on enter button
UI -> GENESIS: inventpory lookup call
GENESIS --> UI: item not found response
UI -> BFF: add item service call
BFF --> UI: invalid bifrost response
UI -> UI: error message on item entry screen 
end
end

group Mylowes lookup
alt valid mylowes lookup
USER -> UI: click on Mylowes lookup
USER -> UI: Enters number
UI -> BFF: customer-management api call
BFF --> UI: customer lookup response
UI -> UI: radio button list for the results
USER -> UI: select radio button and clicks Apply button
UI -> BFF: addCustomerToCart to cart
BFF --> UI: addCustomerToCart response
UI -> UI: customer added to cart with toast notification
end
alt Mylowes lookup for invalid number
USER -> UI: click on Mylowes lookup
USER -> UI: Enters number
UI -> BFF: customer-management api call
BFF --> UI: customer lookup response with no results
UI -> UI: no results found info on mylowes lookup screen
end
end

group Military lookup
alt valid military lookup
USER -> UI: click on military lookup
USER -> UI: Enters number
UI -> BFF: customer-management api call
BFF --> UI: customer lookup response
UI -> UI: radio button list for the results
USER -> UI: select radio button and click continue
UI -> BFF: add military to cart
BFF --> UI: customer added to cart response
UI -> UI: military id verification intervention
UI -> TACHYON: Signal api call(error)
UI -> TACHYON: notify intervention start api call
ASSOCIATE -> UI: clicks on Store Sign In or Scan QR code
UI -> UI: customer id verification with yes or no button option
alt if associate selects no
ASSOCIATE -> UI: selects no option 
UI -> UI: goes back to cart
UI -> TACHYON: Signal api call(normal)
UI -> TACHYON: notify intervention error api call
end
alt if associate selects yes
ASSOCIATE -> UI: selects yes option
UI -> BFF: addCustomerToCart api call
BFF --> UI: customer added to cart response
UI -> TACHYON: Signal api call(normal)
UI -> TACHYON: notify intervention end api call
UI -> UI: shows toast notofication
end
end
alt invalid military lookup
USER -> UI: click on military lookup
USER -> UI: Enters number
UI -> BFF: customer-management api call
BFF --> UI: no results for customner lookup call
UI -> UI: no results found info on military lookup screen
end
end

group scanns empoloyee barcode
alt valid employee scan
USER -> UI: scanns an employee barcode
UI -> BFF: add item call
BFF --> UI: success response for add item call
UI -> UI: Employee added to cart with toast notification
end
alt invalid employee scan
USER -> UI: scanns an employee barcode
UI -> BFF: add item call 
BFF --> UI: barcode not found response
UI -> UI: invalid barcode scanned
end
end

group language swap button click
USER -> UI: clicks Esponal option
UI -> UI: changes UI language to spanish
USER -> UI: clicks English option
UI -> UI: changes UI language to English
end

group get Help button click
USER -> UI: clicks get help button
UI -> TACHYON: Signal api call(error)
UI -> TACHYON: notify assistance start api call
ASSOCIATE -> UI: clicks on the way
UI -> TACHYON: Signal api call
UI -> TACHYON: notify assistance end api call
ASSOCIATE -> UI: logs in to storemode 
UI -> TACHYON: Signal api call
UI -> TACHYON: notify assistance end api call
end

@enduml
