@startuml
actor Customer as USER
actor Associate as ASSOCIATE
participant UI as UI
participant BFF as BFF
participant TACHYON_DM as TACHYON_DM
participant PED as PED
participant CR as CR

USER->UI: Paynow click
group BFF Payment Flow
group activate - [card] with out partial tender
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is true
UI->UI: Tender page on right panel - Amount Due: $xyz
end
group activate - [card] with out partial tender
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is false
UI->BFF: /reviewCart api
note right: check for the api response for partial payments
BFF-->UI: no payments added to the cart
UI->USER: Intervention Login
UI->UI: Unexpected Error occured and close the lane
end
group activate - [card] with partial tender
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is false
UI->BFF: /reviewCart api
note right: check for the api response for partial payments
BFF-->UI: partial payment added to the cart
UI->USER: Intervention login
UI->UI: Partial Amount Info with Manual refund and Got it button.
UI->BFF: /cancelAuthorization
BFF-->UI: cancelAuthorization is success
note right: stop the ped, reset UI states and close lane
end

group activate - [card, cash] with out partial tender both are success
UI->TACHYON_DM: /activate - [CARD, CASH]
TACHYON_DM-->UI: activation status is true
UI->UI: Tender page on right panel - Amount Due: $xyz
end
group activate - [card, cash] with out partial tender either one is success
UI->TACHYON_DM: /activate - [CARD, CASH]
TACHYON_DM-->UI: activation status is false either cash or card
UI->USER: Choose tender modes - proceed with either cash or card
alt - user choice is Yes to continue with either cash or card
UI->UI: Tender page on right panel - Amount Due: $xyz
else - user choice is no
UI->USER: Intenvention login
UI->UI: Suspend Sale / View Cart
end
end
group activate - [card, cash] with partial tender - either one is success
UI->TACHYON_DM: /activate - [CARD, CASH]
TACHYON_DM-->UI: activation status is false
UI->BFF: /reviewCart api
note right: check for the api response for partial payments
BFF-->UI: partial payment added to the cart
UI->USER: Intervention login
UI->UI: Partial Amount Info with Manual refund and Got it button.
UI->BFF: /cancelAuthorization
BFF-->UI: cancelAuthorization is success
UI->TACHYON_DM: /deactivate the activated payment mode
UI->GENSIS:  flip the cart and suspend the sale and print receipt
note right: stop the ped, reset UI states and close lane
end
end

group Genesis tender Flow
group activate - [card] with out partial tender
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is true
UI->UI: Tender page on right panel - Amount Due: $xyz
end
group activate - [card] with out partial tender
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is false
UI->BFF: /contents api
note right: check for the api response for partial payments
BFF-->UI: no payments added to the cart
UI->USER: Intervention Login
UI->UI: Unexpected Error occured and close the lane
end
group activate - [card, cash] with partial tender - either one is success
UI->TACHYON_DM: /activate - [CARD]
TACHYON_DM-->UI: activation status is false
UI->GENSIS: /contents api
note right: check for the api response for partial payments
BFF-->UI: partial payment added to the cart
UI->USER: Intervention login
UI->UI: Partial Amount Info with Manual refund and Got it button.
UI->BFF: /cancelPayment
BFF-->UI: cancelPayment is success
UI->TACHYON_DM: /deactivate the activated payment mode
UI->GENSIS: suspend the sale and print receipt
note right: stop the ped, reset UI states and close lane
end
end

@enduml