@startuml
actor Customer as USER
participant UI as UI
participant BFF as BFF
participant GENESIS as GENESIS
participant TACHYON as TACHYON

== Pro QR code Sale ==
group Pro sale with BFF
group Valid Pro Id scan
USER -> UI: Customer scanned pro qr code.
UI -> BFF: add item call
BFF --> UI: add item api response
note right: BFF cart created and pro id added to cart
UI -> UI: Pro id added to cart
UI -> UI: show toast notification on rihght pannel
USER -> UI: scanned an item.
UI -> BFF: add item api service call
BFF --> UI:  add item success response
note right: work file created with BFF
UI -> UI: Item added to cart
USER -> UI: customer click on paynow button
UI -> BFF: complete api call after payment is done
end

group Expired Pro Id scan
USER -> UI: Customer scanned pro expired qr code.
UI -> BFF: add item service
BFF --> UI: add item response with expiry details
UI -> UI: Show expired Pro Id scanned page with got it button as option
USER -> UI: Clicked on got it button
UI -> UI: return to cart page
end
end

group Pro sale with Genesis
group Valid Pro Id scan
USER -> UI: Customer scanned pro qr code.
UI -> UI: Pro added to cart and toast notification is displayed
USER -> UI: scanned an item.
UI -> GENESIS: add item api service call
GENESIS --> UI:  add item success response
note right: work file created with Genesis
USER -> UI: customer click on paynow button
UI -> GENESIS: sale api comeplete after payement is done
UI -> ORDERS: Pro sale call is made to reders with pro and workfile details
end

group Expired Pro Id scan
USER -> UI: Customer scanned pro expired qr code.
UI -> UI: Show expired Pro Id scanned page with got it button as option
USER -> UI: Clicked on got it button
UI -> UI: return to cart page
end
end